<template>
  <div v-if="visible" class="modal-overlay" @click.self="close">
    <div class="modal-content">
      <h2>About</h2>
      <img
        class="avatar"
        src="https://avatars.githubusercontent.com/u/136006504?v=4"
        alt="Malindu Liyanage"
      />
      <p>The Vesak Thorana was created by <strong>Malindu Liyanage.</strong></p>
      <div class="social-icons">
        <a
          href="https://github.com/MalinduLiyanage"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="GitHub"
        >
          <v-icon icon="mdi-github"></v-icon>
        </a>
        <a
          href="mailto:malindumadhubashana@gmail.com"
          aria-label="Email"
        >
          <v-icon icon="mdi-gmail"></v-icon>
        </a>
        <a
          href="https://fb.com/malindumliyanage"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="FaceBook"
        >
          <v-icon icon="mdi-facebook"></v-icon>
        </a>
        <a
          href="https://www.linkedin.com/in/malindu-liyanage"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="LinkedIn"
        >
          <v-icon icon="mdi-linkedin"></v-icon>
        </a>
      </div>
      <ul class="attribution-list">
        <li>
          Buddha Images are generated by
          <a href="https://grok.com/" target="_blank" rel="noopener noreferrer">Grok AI</a>
        </li>
        <li>
          Background Image:
          <a
            href="https://amazinglanka.com/wp/anuradhapura-tissa-wewa-tank/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Anuradhapura Tissa Wewa
          </a>
        </li>
        <li>
          Jataka tale Audio by
          <a
            href="https://www.youtube.com/watch?v=BhytyQqcRtw&t=158s"
            target="_blank"
            rel="noopener noreferrer"
          >
            Jataka Katha YouTube Channel
          </a>
        </li>
      </ul>
      <div class="powered-by">
        <img
          src="https://miro.medium.com/v2/resize:fit:1400/1*ZFrMIawOvqFH_rBZ2HGWVw.png"
          alt="Powered by Vue and Vuetify"
        />
        <p>Powered By Vue and Vuetify</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  props: {
    visible: {
      type: Boolean,
      required: true,
    },
  },
  emits: ['close'],
  methods: {
    close() {
      this.$emit('close');
    },
  },
});
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2000;
}

.modal-content {
  background: black;
  color: white;
  padding: 2rem;
  border-radius: 10px;
  max-width: 400px;
  text-align: center;
}

.avatar {
  width: 100px;
  height: 100px;
  border-radius: 50%;
  margin: 0 auto 1rem;
  display: block;
  border: 2px solid #42b983;
}

.social-icons {
  margin-bottom: 1rem;
}

.social-icons a {
  color: white;
  margin: 0 0.5rem;
  font-size: 20px;
  transition: color 0.3s;
}

.social-icons a:hover {
  color: #42b983;
}


.attribution-list {
  text-align: left;
  margin: 1rem 0;
  padding-left: 1rem;
}

.attribution-list li {
  margin-bottom: 0.5rem;
  line-height: 1.4;
}

.attribution-list a {
  color: #42b983;
  text-decoration: underline;
}

.powered-by {
  margin-top: 1.5rem;
  text-align: center;
}

.powered-by img {
  max-width: 100px;
  display: block;
  margin: 0 auto 0.5rem;
}
</style>
